# Generated by Django 3.2.4 on 2021-06-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_registration_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='code_reset',
            field=models.BooleanField(default=False),
        ),
    ]
