# Generated by Django 3.2.4 on 2021-06-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_registration_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='code_used',
            new_name='code',
        ),
    ]
