# Generated by Django 3.2.4 on 2021-06-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_registration_code_reset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='code_reset',
        ),
    ]
