# Generated by Django 3.2.4 on 2021-06-24 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_shared_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='shared_from',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared', to='post.post'),
        ),
    ]
