# Generated by Django 3.2.4 on 2021-06-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210620_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hobbies',
            field=models.JSONField(blank=True, default=[]),
        ),
    ]
