# Generated by Django 3.2.4 on 2021-06-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_hobbies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hobbies',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
