# Generated by Django 3.2.4 on 2021-06-22 07:36

import comment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=comment.models.user_directory_path),
        ),
    ]
